// AUTO-GENERATED by scripts/notify.mjs — aggregate of notifications/ (last 30 days).
window.notificationsData = [
  {
    "id": "nms0yatbwva59f",
    "kind": "news",
    "title": "Gate: Jieitai Kanochi nite, Kaku Tatakaeri",
    "kitsuId": "21620",
    "text": "1 new news post.",
    "unread": true,
    "at": "2026-07-25T22:38:47.036Z",
    "time": "4w ago"
  },
  {
    "id": "nms0yatbv39bfv",
    "kind": "news",
    "title": "Shinigami ni Sodaterareta Shoujo wa Shikkoku no Tsurugi wo Mune ni Idaku",
    "kitsuId": "55356",
    "text": "1 new news post.",
    "unread": true,
    "at": "2026-07-25T22:38:47.035Z",
    "time": "4w ago"
  }
];
