// AUTO-GENERATED by scripts/notify.mjs — aggregate of notifications/ (last 30 days).
window.notificationsData = [
  {
    "id": "nmrqxt1w25pj8h",
    "kind": "news",
    "title": "Potion-danomi de Ikinobimasu! Zoku",
    "kitsuId": "71743",
    "text": "1 new news post.",
    "unread": true,
    "at": "2026-07-18T22:27:16.562Z",
    "time": "just now"
  },
  {
    "id": "nmrqxt1w2t320b",
    "kind": "news",
    "title": "Potion-danomi de Ikinobimasu!",
    "kitsuId": "40794",
    "text": "1 new news post.",
    "unread": true,
    "at": "2026-07-18T22:27:16.562Z",
    "time": "just now"
  },
  {
    "id": "nmro2xqs2gi1vb",
    "kind": "news",
    "title": "Buchikire Reijou wa Houfuku wo Chikaimashita. Madousho no Chikara de Sokoku wo Tataki Tsubushimasu",
    "kitsuId": "68690",
    "text": "1 new news post.",
    "unread": true,
    "at": "2026-07-16T22:27:34.994Z",
    "time": "1d ago"
  },
  {
    "id": "nmro2xqs13jqi7",
    "kind": "news",
    "title": "Jujutsu Kaisen",
    "kitsuId": "40815",
    "text": "1 new news post.",
    "unread": true,
    "at": "2026-07-16T22:27:34.993Z",
    "time": "1d ago"
  },
  {
    "id": "nmrid03t446erv",
    "kind": "resumed",
    "title": "Iltagangsa Baeksabu",
    "kitsuId": "62310",
    "text": "Resumed — back to Releasing.",
    "unread": true,
    "at": "2026-07-12T22:22:44.296Z",
    "time": "6d ago"
  },
  {
    "id": "nmrh6c2dj1hd1e",
    "kind": "resumed",
    "title": "Dungeon Odyssey",
    "kitsuId": "64755",
    "text": "Resumed — back to Releasing.",
    "unread": true,
    "at": "2026-07-12T02:28:18.823Z",
    "time": "6d ago"
  }
];
