// AUTO-GENERATED by scripts/healthcheck.mjs — do not edit by hand.
window.sourcesStatus = {
  "checkedAt": "2026-07-23T22:34:54.644Z",
  "services": [
    {
      "mark": "K",
      "name": "Kitsu",
      "role": "Library & reading counts",
      "siteUrl": "kitsu.app",
      "apiUrl": "kitsu.app/api/edge",
      "site": "degraded",
      "api": "up",
      "latency": "213 ms",
      "note": "HTTP 200"
    },
    {
      "mark": "MB",
      "name": "mangabaka",
      "role": "Metadata — genres, tags, news",
      "siteUrl": "mangabaka.org",
      "apiUrl": "api.mangabaka.dev/v1",
      "site": "up",
      "api": "up",
      "latency": "633 ms",
      "note": "HTTP 200"
    }
  ]
};
