// enrich.mjs — the enrichment sync. Runs AFTER sync-library.mjs (which writes
// library.js from Kitsu). For each title it resolves the matching mangabaka
// series and comick comic, then pulls everything we display:
//
//   mangabaka  ->  cover, author, synopsis, status, total chapters,
//                  genres (flat), tags_v2 (weighted) grouped via the tag
//                  dictionary, and news
//   comick     ->  chapter list + release dates (English, de-duplicated)
//
// Output:
//   entries/<kitsuId>.json   full per-title detail read by Entry.html
//   library.js               patched in place with the light fields the
//                            Library grid + notify.mjs need (cover, author,
//                            total, mangabakaStatus, genres, newsCount, ...)
//
// Matching is reliable, not fuzzy: mangabaka results are matched on
// source.kitsu.id and comick on links.kt (the Kitsu id), falling back to the
// top search hit only if no id match is found.
//
// Cost control: each title is cached in its entries/ file and only refreshed
// after REFRESH_DAYS; and at most MAX_PER_RUN titles are (re)enriched per run,
// so a 4x/day cron fills the backlog over a couple of days, then just keeps
// things fresh. Every network call is guarded — failures keep Kitsu values and
// never abort the run.
//
// VERIFY-ON-FIRST-RUN: the two *search* paths below are the one thing I could
// not hit from the build sandbox. If a search 404s, fix SEARCH_MB / SEARCH_CM;
// the series/chapter/news paths are confirmed. Nothing else needs touching.

import fs from 'node:fs';
import path from 'node:path';

const KITSU_ID_FIELD = 'kitsuId';
const REFRESH_DAYS = 7;
const MAX_PER_RUN = 40;
const PACE_MS = 150;

const MB = 'https://api.mangabaka.org';
const CM = 'https://api.comick.dev';
const SEARCH_MB = (q) => `${MB}/v2/series/search?q=${encodeURIComponent(q)}`;      // VERIFY
const SERIES_MB = (id) => `${MB}/v2/series/${id}`;
const NEWS_MB   = (id) => `${MB}/v2/series/${id}/news`;
const SEARCH_CM = (q) => `${CM}/v1.0/search?type=comic&q=${encodeURIComponent(q)}`; // VERIFY
const CHAPS_CM  = (hid, page) => `${CM}/v1.0/comic/${hid}/chapters?page=${page}&limit=100`;
const CM_HEADERS = { Accept: 'application/json', Referer: 'https://comick.dev/', Origin: 'https://comick.dev' };

const LIB_FILE = path.join(process.cwd(), 'library.js');
const TAGS_FILE = path.join(process.cwd(), 'mangabaka_tags.json');
const ENTRIES_DIR = path.join(process.cwd(), 'entries');

// ---- tag dictionary: id -> { name, group, isGenre } -----------------------
function loadTagDict() {
  const dict = {};
  try {
    const arr = JSON.parse(fs.readFileSync(TAGS_FILE, 'utf8')).data || [];
    for (const t of arr) {
      const segs = (t.name_path || t.name || '').split('>').map((s) => s.trim()).filter(Boolean);
      dict[t.id] = {
        name: t.name || segs[segs.length - 1] || '',
        group: t.is_genre ? 'Genre' : (segs.length > 1 ? segs[0] : 'Tag'),
        isGenre: !!t.is_genre,
      };
      if (t.name) dict['name:' + t.name.toLowerCase()] = dict[t.id]; // allow name-keyed lookup too
    }
  } catch (e) { console.warn('tag dictionary unavailable:', e.message); }
  return dict;
}

function parseLibrary() {
  const txt = fs.readFileSync(LIB_FILE, 'utf8');
  const m = txt.match(/window\.libraryData\s*=\s*(\[[\s\S]*\]);/);
  if (!m) return [];
  return (new Function('return ' + m[1]))();
}
function writeLibrary(lib) {
  const header = `// AUTO-GENERATED by scripts/sync-library.mjs + enrich.mjs — do not edit by hand.\n// ${lib.length} entries · enriched ${new Date().toISOString()}\n`;
  fs.writeFileSync(LIB_FILE, `${header}window.libraryData = ${JSON.stringify(lib, null, 2)};\n`);
}

async function getJson(url, headers) {
  const res = await fetch(url + (url.includes('?') ? '&' : '?') + 'cb=' + Date.now(), { headers: headers || { Accept: 'application/json' } });
  if (res.status === 429) throw new Error('429');
  if (!res.ok) throw new Error('HTTP ' + res.status);
  return res.json();
}
const sleep = (ms) => new Promise((r) => setTimeout(r, ms));
const listOf = (j) => (j && (j.data || j.results)) || (Array.isArray(j) ? j : []);

function coverUrl(cover) {
  if (!cover) return '';
  const pick = (v) => (typeof v === 'string' ? v : (v && (v.x2 || v.x1)) || '');
  return pick(cover.x350) || pick(cover.x250) || pick(cover.raw) || pick(cover.x150) || '';
}
function mapStatus(s) {
  if (!s) return '';
  s = String(s).toLowerCase();
  if (s.includes('releasing') || s.includes('ongoing')) return 'Releasing';
  if (s.includes('complete') || s.includes('finished')) return 'Completed';
  if (s.includes('hiatus')) return 'Hiatus';
  if (s.includes('cancel')) return 'Cancelled';
  return s.charAt(0).toUpperCase() + s.slice(1);
}

// weighted + grouped tags from a series' tags_v2 using the dictionary
function buildTags(series, dict) {
  const raw = series.tags_v2 || series.tags || [];
  const out = [];
  for (const t of raw) {
    const id = (t && (t.id ?? t.tag_id));
    const nm = (t && (t.name || t.tag)) || '';
    const info = (id != null && dict[id]) || dict['name:' + String(nm).toLowerCase()] || null;
    out.push({
      name: (info && info.name) || nm || String(id),
      group: (info && info.group) || 'Tag',
      weight: (t && (t.weight || t.rank)) || 'unweighted',
    });
  }
  return out;
}

async function resolveMangabaka(item, dict) {
  const results = listOf(await getJson(SEARCH_MB(item.title)));
  if (!results.length) return null;
  const kid = String(item[KITSU_ID_FIELD] || '');
  let hit = results.find((r) => r && r.source && r.source.kitsu && String(r.source.kitsu.id) === kid) || results[0];
  const id = hit && hit.id;
  if (!id) return null;
  await sleep(PACE_MS);
  const d = (await getJson(SERIES_MB(id))).data || {};
  let news = [];
  try {
    await sleep(PACE_MS);
    news = listOf(await getJson(NEWS_MB(id))).map((n) => ({
      title: n.title || n.headline || '', date: n.date || n.published || n.created_at || '', url: n.url || n.link || '',
    }));
  } catch { /* news optional */ }
  return {
    mangabakaId: id,
    cover: coverUrl(d.cover),
    author: Array.isArray(d.authors) ? d.authors.join(', ') : (d.authors || ''),
    synopsis: d.description || '',
    status: mapStatus(d.status),
    total: Number(d.total_chapters) || null,
    genres: Array.isArray(d.genres) ? d.genres.map((g) => (typeof g === 'string' ? g : g.name)).filter(Boolean) : [],
    tags: buildTags(d, dict),
    news,
  };
}

function dedupeChapters(chapters) {
  const byNum = new Map();
  for (const c of chapters) {
    if ((c.lang || c.iso639_1) !== 'en') continue;
    const num = c.chap != null ? String(c.chap) : (c.chapter != null ? String(c.chapter) : null);
    if (num === null) continue;
    const up = Number(c.up_count) || 0;
    const prev = byNum.get(num);
    if (!prev || up > prev._up) byNum.set(num, { num, title: c.title || '', date: c.created_at || c.updated_at || '', _up: up });
  }
  return Array.from(byNum.values())
    .map((c) => ({ num: c.num, title: c.title, date: c.date }))
    .sort((a, b) => parseFloat(b.num) - parseFloat(a.num));
}

async function resolveComick(item) {
  const results = listOf(await getJson(SEARCH_CM(item.title), CM_HEADERS));
  if (!results.length) return null;
  const kid = String(item[KITSU_ID_FIELD] || '');
  let hit = results.find((r) => r && r.links && String(r.links.kt) === kid) || results[0];
  const hid = hit && hit.hid;
  if (!hid) return null;
  let all = [], page = 1, guardTotal = Infinity;
  while (page <= 10) {                        // cap ~1000 chapters
    await sleep(PACE_MS);
    const j = await getJson(CHAPS_CM(hid, page), CM_HEADERS);
    const chs = listOf(j);
    if (!chs.length) break;
    all = all.concat(chs);
    guardTotal = j.total || guardTotal;
    if (all.length >= guardTotal) break;
    page++;
  }
  return { comickHid: hid, chapters: dedupeChapters(all) };
}

function isFresh(kitsuId) {
  try {
    const j = JSON.parse(fs.readFileSync(path.join(ENTRIES_DIR, kitsuId + '.json'), 'utf8'));
    return j.updatedAt && (Date.now() - new Date(j.updatedAt).getTime() < REFRESH_DAYS * 86400000);
  } catch { return false; }
}

async function main() {
  if (!fs.existsSync(LIB_FILE)) { console.warn('library.js missing — run sync-library.mjs first.'); return; }
  if (!fs.existsSync(ENTRIES_DIR)) fs.mkdirSync(ENTRIES_DIR, { recursive: true });
  const dict = loadTagDict();
  const lib = parseLibrary();

  let done = 0, fails = 0;
  for (const item of lib) {
    const kid = String(item[KITSU_ID_FIELD] || item.slug || item.title || '');
    if (!kid) continue;
    if (isFresh(kid)) { patchFromEntry(item, kid); continue; }
    if (done >= MAX_PER_RUN) break;
    if (fails >= 6) { console.warn('too many failures — stopping this run, will resume next time'); break; }

    const entry = { kitsuId: kid, title: item.title, updatedAt: new Date().toISOString() };
    let ok = false;
    try { const mb = await resolveMangabaka(item, dict); if (mb) { Object.assign(entry, mb); ok = true; } }
    catch (e) { fails++; }
    try { const cm = await resolveComick(item); if (cm) { Object.assign(entry, cm); ok = true; } }
    catch (e) { /* comick optional */ }

    if (ok) {
      fs.writeFileSync(path.join(ENTRIES_DIR, kid + '.json'), JSON.stringify(entry, null, 2));
      applyToLibrary(item, entry);
      done++; fails = 0;
    }
    await sleep(PACE_MS);
  }

  writeLibrary(lib);
  console.log(`enrich: ${done} title(s) enriched this run (cap ${MAX_PER_RUN}).`);
}

// light fields onto the library row (grid + notifications need these)
function applyToLibrary(item, e) {
  if (e.cover) item.cover = e.cover;
  if (e.author && !item.author) item.author = e.author;
  if (e.total && !item.total) item.total = e.total;
  if (e.status) item.mangabakaStatus = e.status;
  if (e.genres) item.genres = e.genres;
  if (Array.isArray(e.news)) item.newsCount = e.news.length;
  if (Array.isArray(e.chapters)) item.chapterCount = e.chapters.length;
}
function patchFromEntry(item, kid) {
  try { applyToLibrary(item, JSON.parse(fs.readFileSync(path.join(ENTRIES_DIR, kid + '.json'), 'utf8'))); } catch {}
}

main();
