// healthcheck.mjs — pings each upstream service (website + API) from the
// GitHub runner and writes sources_status.js, which the Sources page reads.
// Runs server-side so it isn't blocked by the browser CORS rules that stop
// the page from checking mangabaka/comick directly.

import fs from 'node:fs';
import path from 'node:path';

const OUT_FILE = path.join(process.cwd(), 'sources_status.js');
const TIMEOUT_MS = 8000;

// Each service: a website URL and an API URL to probe.
const SERVICES = [
  { mark: 'K',  name: 'Kitsu',     role: 'Library & reading counts',
    siteUrl: 'kitsu.app',        site: 'https://kitsu.app',
    apiUrl: 'kitsu.app/api/edge', api: 'https://kitsu.app/api/edge/users/1699796/stats',
    apiHeaders: { Accept: 'application/vnd.api+json' } },
  { mark: 'MB', name: 'mangabaka', role: 'Metadata — genres, tags, news',
    siteUrl: 'mangabaka.org',    site: 'https://mangabaka.org',
    apiUrl: 'api.mangabaka.org/v2', api: 'https://api.mangabaka.org/v2/series/9745',
    apiHeaders: { Accept: 'application/json' } },
  { mark: 'CM', name: 'comick',    role: 'Chapter listings & release dates',
    siteUrl: 'comick.dev',       site: 'https://comick.dev',
    apiUrl: 'api.comick.dev/v1.0', api: 'https://api.comick.dev/v1.0/search?q=test&limit=1',
    apiHeaders: { Accept: 'application/json', Referer: 'https://comick.dev/' } },
];

async function probe(url, headers) {
  const started = Date.now();
  const ctrl = new AbortController();
  const timer = setTimeout(() => ctrl.abort(), TIMEOUT_MS);
  try {
    const res = await fetch(url + (url.includes('?') ? '&' : '?') + 'cb=' + Date.now(),
      { headers: headers || {}, signal: ctrl.signal, redirect: 'follow' });
    const ms = Date.now() - started;
    let state = 'up';
    if (res.status === 429 || res.status === 403) state = 'degraded';     // rate-limited / referer-gated
    else if (res.status >= 500) state = 'down';
    else if (res.status >= 400) state = 'degraded';
    return { state, ms, note: 'HTTP ' + res.status };
  } catch (err) {
    return { state: 'down', ms: Date.now() - started, note: err.name === 'AbortError' ? 'timeout' : 'unreachable' };
  } finally {
    clearTimeout(timer);
  }
}

async function main() {
  const services = [];
  for (const s of SERVICES) {
    const siteR = await probe(s.site);
    const apiR = await probe(s.api, s.apiHeaders);
    // Report the slower of the two probes as the headline latency.
    const latency = Math.max(siteR.ms, apiR.ms) + ' ms';
    let note = apiR.note;
    if (s.name === 'comick' && apiR.state === 'degraded') note = 'referer-gated · rate-limited';
    services.push({
      mark: s.mark, name: s.name, role: s.role,
      siteUrl: s.siteUrl, apiUrl: s.apiUrl,
      site: siteR.state, api: apiR.state,
      latency, note,
    });
  }
  const payload = { checkedAt: new Date().toISOString(), services };
  const header = `// AUTO-GENERATED by scripts/healthcheck.mjs — do not edit by hand.\n`;
  fs.writeFileSync(OUT_FILE, `${header}window.sourcesStatus = ${JSON.stringify(payload, null, 2)};\n`);
  console.log('Wrote sources_status.js:', services.map(s => `${s.name}=${s.api}`).join(', '));
}

main();
